<?php

/**
 * @file
 * Module file for mypager.
 */

use Drupal\Core\Url;
use Drupal\Core\Template\Attribute;
use Drupal\mypager\Plugin\views\pager\Mypager;
use Drupal\Core\Render\Markup;


/**
 * Implements hook_preprocess_mypager_pager().
 */
function template_preprocess_mypager_pager(&$variables) {
  $element = $variables['element'];
  $parameters = $variables['parameters'];

  /* @var $pager_manager \Drupal\Core\Pager\PagerManagerInterface */
  $pager_manager = \Drupal::service('pager.manager');
  $pager = $pager_manager->getPager($element);

  if ($pager->getCurrentPage() < ($pager->getTotalPages() - 1)) {
    $options = array(
      'query' => $pager_manager->getUpdatedParameters($parameters, $element, $pager->getCurrentPage() + 1),
    );
    $variables['items']['next']['href'] = Url::fromRoute('<current>', [], $options);
  }
  $variables['#cache']['contexts'][] = 'url.query_args';
  $variables['attributes'] = new Attribute([
    'class' => ['js-pager__items', 'pager'],
  ]);
  $count_new_load = $pager->getLimit() - ($pager->getTotalPages() * $pager->getLimit() - $pager->getTotalItems());
  if (empty($count_new_load)) {
    $count_new_load = $pager->getLimit();
  }
  if ($pager->getCurrentPage() < ($pager->getTotalPages() - 2)) {
    $count_new_load = $pager->getLimit();
  }
  $button_text = str_replace('@count', ' <span>' . $count_new_load . '</span>', $variables['options']['mypager']['button_text']);
  $variables['options']['mypager']['button_text'] = Markup::create($button_text);
}


/**
 * Implements hook_preprocess_pager().
 */
function mypager_preprocess_pager(&$variables) {
  $element = $variables['pager']['#element'];
  /* @var $pager_manager \Drupal\Core\Pager\PagerManagerInterface */
  $pager_manager = \Drupal::service('pager.manager');
  $pager = $pager_manager->getPager($element);
  if ($pager) {
    $variables['options']['max_page_number'] = $pager->getTotalPages();
    // $variables['#attached']['drupalSettings']['mypager'][$element]['currents'] = $variables['current'];
  }
}


/**
 * Implements hook_preprocess_views_view().
 */
function mypager_preprocess_views_view(&$variables) {
  /* @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  if ($view->getDisplay()->isPagerEnabled() && !empty($variables['rows'])) {
    $pager = $view->getPager();
    if ($pager && $pager instanceof Mypager) {
      $variables['rows']['#theme_wrappers'] = ['container'];
      $variables['rows']['#attributes'] = [
        'data-drupal-views-mypager-content-wrapper' => TRUE,
        'class' => [
          'views-mypager-content-wrapper',
          'clearfix',
        ],
      ];
    }
  }
}
