<?php

/**
 * @file
 * Module file for mypager.
 */

use Drupal\Core\Url;
use Drupal\Core\Template\Attribute;
use Drupal\mypager\Plugin\views\pager\Mypager;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_preprocess_mypager_pager().
 */
function mypager_preprocess_mypager_pager(&$vars) {
  global $pager_page_array, $pager_total, $pager_total_items, $pager_limits;
  $element = $vars['element'];
  $parameters = $vars['parameters'];
  if ($pager_page_array[$element] < ($pager_total[$element] - 1)) {
    $options = array(
      'query' => pager_query_add_page($parameters, $element, $pager_page_array[$element] + 1),
    );
    $vars['items']['next']['href'] = Url::fromRoute('<current>', [], $options);
  }
  $vars['#cache']['contexts'][] = 'url.query_args';
  $vars['attributes'] = new Attribute([
    'class' => ['js-pager__items', 'pager'],
    'data-drupal-views-mypager' => TRUE,
  ]);



  $count_new_load = $pager_limits[$element] - ($pager_total[$element] * $pager_limits[$element] - $pager_total_items[$element]);
  if (empty($count_new_load)) {
    $count_new_load = $pager_limits[$element];
  }
  if ($pager_page_array[$element] < ($pager_total[$element] - 2)) {
    $count_new_load = $pager_limits[$element];
  }
  $button_text = str_replace('@count', ' <span>' . $count_new_load . '</span>', $vars['options']['mypager']['button_text']);
  $vars['options']['mypager']['button_text'] = Markup::create($button_text);






}




/**
 * Implements hook_preprocess_views_view().
 */
function mypager_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  if ($view->getDisplay()->isPagerEnabled() && !empty($vars['rows'])) {
    $pager = $view->getPager();
    if ($pager && $pager instanceof Mypager) {
      $vars['rows']['#theme_wrappers'] = ['container'];
      $vars['rows']['#attributes'] = [
        'data-drupal-views-mypager-content-wrapper' => TRUE,
        'class' => [
          'views-mypager-content-wrapper',
          'clearfix',
        ],
      ];
    }
  }
}
